package com.example.sabdar.project7.data;

import android.content.ContentResolver;
import android.net.Uri;
import android.provider.BaseColumns;

public final class InventoryContract {
    // To prevent someone from accidentally instantiating the contract class,
    // give it an empty constructor.
    private InventoryContract() {
    }

    public static final String CONTENT_AUTHORITY = "com.example.sabdar.project7";
    public static final Uri BASE_CONTENT_URI = Uri.parse("content://" + CONTENT_AUTHORITY);
    public static final String PATH_INVENTORY = "inventory";

    public static final class InventoryEntry implements BaseColumns {

        public static final Uri CONTENT_URI = Uri.withAppendedPath(BASE_CONTENT_URI, PATH_INVENTORY);

        public static final String CONTENT_LIST_TYPE = ContentResolver.CURSOR_DIR_BASE_TYPE +"/"+ CONTENT_AUTHORITY +"/"+ PATH_INVENTORY;

        public static final String CONTENT_ITEM_TYPE = ContentResolver.CURSOR_ITEM_BASE_TYPE +"/"+ CONTENT_AUTHORITY +"/"+ PATH_INVENTORY;

        //table name
        public static final String TABLE_NAME = "inventory";
        // row Id  generated by auto increment when inserting new product data
        public static final String _ID = BaseColumns._ID;
        //column name for Product Name
        public static final String COLUMN_PRODUCT_NAME = "product_name";
        //column name for Price
        public static final String COLUMN_PRICE = "price";
        //column name for Quantity
        public static final String COLUMN_QUANTITY = "quantity";
        //column name for Supplier Name
        public static final String COLUMN_SUPPLIER_NAME = "supplier_name";
        //column name for Supplier Phone Number
        public static final String COLUMN_SUPPLIER_PHONE_NUMBER = "supplier_phone_number";

    }
}
