package com.example.sabdar.project7.data;

import android.provider.BaseColumns;

public final class InventoryContract {
    private InventoryContract() {
    }

    public static final class InventoryEntry implements BaseColumns {
        //table name
        public static final String TABLE_NAME = "inventory";
        // row Id  generated by auto increment when inserting new product data
        public static final String _ID = BaseColumns._ID;
        //column name for Product Name
        public static final String COLUMN_PRODUCT_NAME = "product_name";
        //column name for Price
        public static final String COLUMN_PRICE = "price";
        //column name for Quantity
        public static final String COLUMN_QUANTITY = "quantity";
        //column name for Supplier Name
        public static final String COLUMN_SUPPLIER_NAME = "supplier_name";
        //column name for Supplier Phone Number
        public static final String COLUMN_SUPPLIER_PHONE_NUMBER = "supplier_phone_number";

    }
}
